version: '3.2'
services:
    webapp:
        image: dtr.olly.dtcntr.net/fakeco-prod/demo-app:latest
        networks: 
            - backend
        ports:
            - 30002
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == worker]

networks:
    backend:
        driver: overlay

