version: '3.1'
services:
        webapp:
                image: 52.56.228.3/admin/test:"${commit_id}"
                deploy:
                        mode: replicated
                        replicas: 1
                ports:
                        - 30001:80
